units:
  # Proxy Spacing Variables
  kx: cx
  ky: cy
  # Padding Variables
  px: kx + 2
  py: ky + 2
points:
  zones:
    matrix:
      key:
        padding: 1ky
        spread: 1kx
      anchor:
        rotate: 5
      columns:
        outer:
          key.column_net: P100
        pinky:
          key.column_net: P011
        ring:
          key.splay: -5
          key.origin: [-0.75ky, -py]
          key.stagger: 0.75ky
          key.column_net: P104
        middle:
          key.splay: -5
          key.origin: [0, -ky]
          key.stagger: 0.25ky
          key.column_net: P106
        index:
          key.splay: 0
          key.stagger: -0.5ky
          key.column_net: P111
        inner:
          key.stagger: -0.25ky
          key.column_net: P010
        bracket:
          rows:
            num.skip: true
            top.skip: true
            bottom.skip: true
          key.column_net: P009
      rows:
        bottom:
          row_net: P115
        home:
          row_net: P002
        top:
          row_net: P24
        num:
          row_net: P22
    thumbfan:
      anchor:
        ref: matrix_inner_bottom
        shift: [0, -23]
      columns:
        near:
          key.splay: -28
          key.column_net: P111
        home:
          key.spread: 21.25
          key.splay: -10
          key.origin: [-11.75, -9]
          key.column_net: P010
      rows:
        thumb:
          row_net: P113
  rotate: 5
outlines:
  raw:
    - what: rectangle
      where: true
      size: [kx, ky]
  nnv2:
    - what: rectangle
      size: [34.1, 18.3]
      operation: stack
      adjust:
        ref: matrix_outer_num
        shift: [9, py+1]
  keys:
    - what: rectangle
      where: true
      size: [kx-0.5, ky-0.5]
  board:
    - what: polygon
      operation: stack
      fillet: 2
      points:
        - ref: matrix_outer_num
          shift: [-0.5px,0.5py+22]
        - ref: matrix_pinky_num
          shift: [0.5px,0.5py+22]
        - ref: matrix_bracket_home
          shift: [0.5px,2.7py+6.7]
        - ref: matrix_bracket_home
          shift: [0.5px,-0.5py]
        - ref: matrix_bracket_home
          shift: [0.5px,-2.5py]
        - ref: thumbfan_home_thumb
          shift: [0.5px,0.5py]
        - ref: thumbfan_home_thumb
          shift: [0.5px,-0.5py]
        - ref: thumbfan_home_thumb
          shift: [-0.5px,-0.5py]
        - ref: thumbfan_near_thumb
          shift: [0.5kx,-0.5py]
        - ref: thumbfan_near_thumb
          shift: [-0.3px,-0.5py]
        - ref: matrix_middle_bottom
          shift: [-1,-2.15py-0.47]
        - ref: matrix_pinky_bottom
          shift: [0.5px,-0.5py]
        - ref: matrix_outer_bottom
          shift: [-0.5px,-0.5py]
  combo:
    - name: board
    - operation: subtract
      name: keys
    - operation: subtract
      name: nnv2
pcbs:
  board:
    outlines:
      main:
        outline: board
    footprints:
      choc_hotswap:
        what: choc
        where: true
        params:
          keycaps: true
          reverse: true
          hotswap: true
          from: "{{column_net}}"
          to: "{{colrow}}"
      diode:
        what: smd_diode
        where: true
        params:
          from: "{{colrow}}"
          to: "{{row_net}}"
        adjust:
          shift: [0, -5]
      nicenano:
        what: nice_nano_pretty
        where:
          ref: matrix_outer_num
          shift: [8, py+1]
      reset:
        what: button
        params:
          from: GND
          to: RST
        where:
          ref: thumbfan_home_thumb
          shift: [0.3px, 1.3py-1.5]
          rotate: -38
      trackball:
        what: pimoroni_trackball_reversible
        params:
          VCC: VCC
          SDA: P017
          SCL: P020
          GND: GND
        where:
          ref: matrix_index_bottom
          shift: [-0.5px-1, -1.5py-2]
          rotate: 90
      battery:
        what: jstph_no_silks
        params:
          pos: RAW
          neg: GND
        where:
          ref: matrix_inner_num
          shift: [0, 1py]
      holeTopLeft:
        what: mountinghole
        where:
          ref: matrix_pinky_num
          shift: [0.6kx, 1.6ky]
      holeBottomLeft:
        what: mountinghole
        where:
          ref: matrix_pinky_bottom
          shift: [0.8kx, -0.2ky]
      holeTopRight:
        what: mountinghole
        where:
          ref: matrix_bracket_home
          shift: [0.5px-4,2.7py+2.7]
      holeBottomRight:
        what: mountinghole
        where:
          ref: matrix_bracket_home
          shift: [0.5px-4, -1.5ky-0.3]